# Generated by Django 3.1.3 on 2020-12-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201207_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='PathwayName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentEnglishPassed',
            field=models.BooleanField(default='true'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentMathsPassed',
            field=models.BooleanField(default='true'),
        ),
    ]
