# Generated by Django 3.1.3 on 2020-12-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201207_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=12)),
                ('studentForename', models.CharField(max_length=56)),
                ('studentSurname', models.CharField(max_length=256)),
                ('studentContactnumber', models.CharField(max_length=11)),
                ('studentEmail', models.EmailField(max_length=256)),
                ('studentEnglishPassed', models.BooleanField(default='true')),
                ('studentMathsPassed', models.BooleanField(default='true')),
                ('studentUCASvalue', models.CharField(max_length=20)),
                ('PathwayName', models.CharField(default='Networking', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='PathwayName',
            field=models.CharField(default='Software Engineering', max_length=256),
        ),
    ]
