# Generated by Django 3.1.3 on 2020-12-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201207_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentContactnumber',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentEmail',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentForename',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentSurname',
            field=models.CharField(max_length=256),
        ),
    ]
