# Generated by Django 3.1.3 on 2020-12-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201207_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentNE',
        ),
        migrations.AlterField(
            model_name='student',
            name='PathwayName',
            field=models.CharField(default='', max_length=256),
        ),
    ]
