# Generated by Django 3.1.3 on 2020-12-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20201209_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentID',
            new_name='studentUsername',
        ),
    ]
