# Generated by Django 3.1.3 on 2020-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201209_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='CourseName',
            field=models.CharField(choices=[('LGA1', 'Critical Analysis'), ('LGA2', 'Technical Documentation'), ('LGA3', 'Team Work'), ('LGA4', 'Time Management'), ('LGA5', 'Software Applications')], default='1', max_length=256),
        ),
    ]
