# Generated by Django 3.1.3 on 2020-12-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_student_coursename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='CourseName',
        ),
        migrations.AddField(
            model_name='student',
            name='Course01Name',
            field=models.CharField(choices=[('LGA1', '1 - Strongly Agree'), ('LGA2', '2 - Agree'), ('LGA3', '3 - Unsure'), ('LGA4', '4 - Disagree'), ('LGA5', '5 - Strongly Disagree')], default='Critical Analysis', max_length=256),
        ),
        migrations.AddField(
            model_name='student',
            name='Course02Name',
            field=models.CharField(choices=[('LGA1', '1 - Strongly Agree'), ('LGA2', '2 - Agree'), ('LGA3', '3 - Unsure'), ('LGA4', '4 - Disagree'), ('LGA5', '5 - Strongly Disagree')], default='Technical Documentation', max_length=256),
        ),
        migrations.AddField(
            model_name='student',
            name='Course03Name',
            field=models.CharField(choices=[('LGA1', '1 - Strongly Agree'), ('LGA2', '2 - Agree'), ('LGA3', '3 - Unsure'), ('LGA4', '4 - Disagree'), ('LGA5', '5 - Strongly Disagree')], default='Team Work', max_length=256),
        ),
        migrations.AddField(
            model_name='student',
            name='Course04Name',
            field=models.CharField(choices=[('LGA1', '1 - Strongly Agree'), ('LGA2', '2 - Agree'), ('LGA3', '3 - Unsure'), ('LGA4', '4 - Disagree'), ('LGA5', '5 - Strongly Disagree')], default='Time Management', max_length=256),
        ),
        migrations.AddField(
            model_name='student',
            name='Course05Name',
            field=models.CharField(choices=[('LGA1', '1 - Strongly Agree'), ('LGA2', '2 - Agree'), ('LGA3', '3 - Unsure'), ('LGA4', '4 - Disagree'), ('LGA5', '5 - Strongly Disagree')], default='Software Applications', max_length=256),
        ),
    ]
