# Generated by Django 3.1.3 on 2020-12-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20201215_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Course01Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Course02Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Course03Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Course04Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Course05Name',
        ),
        migrations.AddField(
            model_name='student',
            name='CriticalAnalysis',
            field=models.CharField(choices=[('LGA1', '1 - Strongly Agree'), ('LGA2', '2 - Agree'), ('LGA3', '3 - Unsure'), ('LGA4', '4 - Disagree'), ('LGA5', '5 - Strongly Disagree')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='student',
            name='SoftwareApplications',
            field=models.CharField(choices=[('LGA1', '1 - Strongly Agree'), ('LGA2', '2 - Agree'), ('LGA3', '3 - Unsure'), ('LGA4', '4 - Disagree'), ('LGA5', '5 - Strongly Disagree')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='student',
            name='TeamWork',
            field=models.CharField(choices=[('LGA1', '1 - Strongly Agree'), ('LGA2', '2 - Agree'), ('LGA3', '3 - Unsure'), ('LGA4', '4 - Disagree'), ('LGA5', '5 - Strongly Disagree')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='student',
            name='TechnicalDocumentation',
            field=models.CharField(choices=[('LGA1', '1 - Strongly Agree'), ('LGA2', '2 - Agree'), ('LGA3', '3 - Unsure'), ('LGA4', '4 - Disagree'), ('LGA5', '5 - Strongly Disagree')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='student',
            name='TimeManagement',
            field=models.CharField(choices=[('LGA1', '1 - Strongly Agree'), ('LGA2', '2 - Agree'), ('LGA3', '3 - Unsure'), ('LGA4', '4 - Disagree'), ('LGA5', '5 - Strongly Disagree')], default='', max_length=256),
        ),
    ]
