# Generated by Django 3.1.3 on 2020-12-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20201215_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='SoftwareApplications',
            field=models.CharField(choices=[('LGA1', '1 - Strongly Agree'), ('LGA2', '2 - Agree'), ('LGA3', '3 - Unsure'), ('LGA4', '4 - Disagree'), ('LGA5', '5 - Strongly Disagree')], default='', max_length=256, verbose_name='test string'),
        ),
    ]
