# Generated by Django 3.1.3 on 2020-12-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20201215_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='CriticalAnalysis',
        ),
        migrations.RemoveField(
            model_name='student',
            name='SoftwareApplications',
        ),
        migrations.RemoveField(
            model_name='student',
            name='TeamWork',
        ),
        migrations.RemoveField(
            model_name='student',
            name='TechnicalDocumentation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='TimeManagement',
        ),
        migrations.AddField(
            model_name='student',
            name='LGA1',
            field=models.CharField(choices=[('LGAc1', '1 - Strongly Agree'), ('LGAc2', '2 - Agree'), ('LGAc3', '3 - Unsure'), ('LGAc4', '4 - Disagree'), ('LGAc5', '5 - Strongly Disagree')], default='', max_length=256, verbose_name='Critical Analysis'),
        ),
        migrations.AddField(
            model_name='student',
            name='LGA2',
            field=models.CharField(choices=[('LGAc1', '1 - Strongly Agree'), ('LGAc2', '2 - Agree'), ('LGAc3', '3 - Unsure'), ('LGAc4', '4 - Disagree'), ('LGAc5', '5 - Strongly Disagree')], default='', max_length=256, verbose_name='Technical Documentation'),
        ),
        migrations.AddField(
            model_name='student',
            name='LGA3',
            field=models.CharField(choices=[('LGAc1', '1 - Strongly Agree'), ('LGAc2', '2 - Agree'), ('LGAc3', '3 - Unsure'), ('LGAc4', '4 - Disagree'), ('LGAc5', '5 - Strongly Disagree')], default='', max_length=256, verbose_name='Team Work'),
        ),
        migrations.AddField(
            model_name='student',
            name='LGA4',
            field=models.CharField(choices=[('LGAc1', '1 - Strongly Agree'), ('LGAc2', '2 - Agree'), ('LGAc3', '3 - Unsure'), ('LGAc4', '4 - Disagree'), ('LGAc5', '5 - Strongly Disagree')], default='', max_length=256, verbose_name='Time Management'),
        ),
        migrations.AddField(
            model_name='student',
            name='LGA5',
            field=models.CharField(choices=[('LGAc1', '1 - Strongly Agree'), ('LGAc2', '2 - Agree'), ('LGAc3', '3 - Unsure'), ('LGAc4', '4 - Disagree'), ('LGAc5', '5 - Strongly Disagree')], default='', max_length=256, verbose_name='Software Applications'),
        ),
    ]
