# Generated by Django 3.1.4 on 2020-12-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', help_text='This information will be used to log you into the website later', max_length=56)),
                ('Password', models.CharField(default='', help_text='This information will be used to log you into the website later', max_length=48)),
                ('studentForename', models.CharField(max_length=56)),
                ('studentSurname', models.CharField(max_length=256)),
                ('studentContactnumber', models.IntegerField(default='+44', help_text='What is your Primary contact number', verbose_name='Contact Number')),
                ('studentEmail', models.EmailField(max_length=256)),
                ('studentEnglish', models.BooleanField(default='True', verbose_name='You hold a level 4/Grade C or above in English')),
                ('studentMaths', models.BooleanField(default='True', verbose_name='You hold a level 4/Grade C or above in Maths')),
                ('TotalUCAS', models.IntegerField(default=0, help_text='What is your total number of UCAS points? (At least 104 needed to apply for a Undergraduate Course)', verbose_name='UCAS Points')),
                ('PathwayName', models.CharField(choices=[('SO', 'Software Engineering'), ('NE', 'Networking'), ('CO', 'Computing'), ('GD', 'Graphic Design'), ('TE', 'Teacher Education'), ('PE', 'Physical Education'), ('PY', 'Psychology')], max_length=256)),
                ('LGA1', models.CharField(choices=[('1', '1 - Very Confident with Critical Analysis'), ('2', '2 - Confident with Critical Analysis'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Not Confident with Critical Analysis (Auto-Enrol)'), ('5', '5 - No Prior Knowledge of Critical Analysis (Auto-Enrol)')], default='', help_text='If you score 3 or higher you will be enroled on the Critical Analysis short course for free. (Cource Reference UOBSCCA2021)', max_length=256, verbose_name='Critical Analysis')),
                ('LGA2', models.CharField(choices=[('1', '1 - Very Confident with Technical Documentation'), ('2', '2 - Confident with Technical Documentation'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Not Confident with Technical Documentation (Auto-Enrol)'), ('5', '5 - No Prior use of Technical Documentation (Auto-Enrol)')], default='', help_text='If you score 3 or higher you will be enroled on the Technical Documentation short course for free. (Cource Reference UOBSCTD2021)', max_length=256, verbose_name='Technical Documentation')),
                ('LGA3', models.CharField(choices=[('1', '1 - Very Confident with working in a team'), ('2', '2 - Confident with working in a team'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Not Confident with working in a team (Auto-Enrol)'), ('5', '5 - No Prior Experience of working in a team (Auto-Enrol)')], default='', help_text='If you score 3 or higher you will be enroled on the Team Work & Communication short course for free. (Cource Reference UOBSCTW2021)', max_length=256, verbose_name='Team Work & Communication')),
                ('LGA4', models.CharField(choices=[('1', '1 - Very Confident with Time Management'), ('2', '2 - Confident with Time Management'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Not Confident with Time Management (Auto-Enrol)'), ('5', '5 - No Prior Knowledge of Time Management practices (Auto-Enrol)')], default='', help_text='If you score 3 or higher you will be enroled on the Time Management short course for free. (Cource Reference UOBSCTM2021)', max_length=256, verbose_name='Time Management')),
                ('LGA5', models.CharField(choices=[('1', '1 - Very Confident with Word Processing and Database Applications'), ('2', '2 - Confident with Word Processing and Database Applications'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Not Confident with Word Processing and Database Applications (Auto-Enrol)'), ('5', '5 - No Prior Knowledge of Word Processing and Database Applications (Auto-Enrol)')], default='', help_text='If you score 3 or higher you will be enroled on the Computer Applications short course for free. (Cource Reference UOBSCCA2021)', max_length=256, verbose_name='Word Processing and Database Applications')),
                ('SupCourse01', models.BooleanField(default='False', verbose_name='Critical Analysis')),
                ('SupCourse02', models.BooleanField(default='False', verbose_name='Technical Documentation')),
                ('SupCourse03', models.BooleanField(default='False', verbose_name='Team Work')),
                ('SupCourse04', models.BooleanField(default='False', verbose_name='Time Management')),
                ('SupCourse05', models.BooleanField(default='False', verbose_name='Computer Applications')),
            ],
        ),
    ]
