# Generated by Django 3.1.4 on 2020-12-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentContactnumber',
            field=models.CharField(default='+44', help_text='What is your Primary contact number', max_length=11, verbose_name='Contact Number'),
        ),
    ]
