# Generated by Django 3.1.3 on 2020-12-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentUsername', models.CharField(max_length=12)),
                ('studentForename', models.CharField(max_length=56)),
                ('studentSurname', models.CharField(max_length=256)),
                ('studentContactnumber', models.CharField(max_length=11)),
                ('studentEmail', models.EmailField(max_length=256)),
                ('studentEnglish', models.BooleanField(default='True', verbose_name='You hold a level 4/Grade C or above in English')),
                ('studentMaths', models.BooleanField(default='True', verbose_name='You hold a level 4/Grade C or above in Maths')),
                ('TotalUCAS', models.CharField(default=0, max_length=20, verbose_name='What is your total number of UCAS points?')),
                ('PathwayName', models.CharField(choices=[('SO', 'Software Engineering'), ('NE', 'Networking')], max_length=256)),
                ('LGA1', models.CharField(choices=[('1', '1 - Strongly Agree'), ('2', '2 - Agree'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Disagree (Auto-Enrol)'), ('5', '5 - Strongly Disagree (Auto-Enrol)')], default='', max_length=256, verbose_name='I am confident in my knowledge and usage of Critical Analysis')),
                ('LGA2', models.CharField(choices=[('1', '1 - Strongly Agree'), ('2', '2 - Agree'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Disagree (Auto-Enrol)'), ('5', '5 - Strongly Disagree (Auto-Enrol)')], default='', max_length=256, verbose_name='I am confident in my knowledge and usage of Technical Documentation')),
                ('LGA3', models.CharField(choices=[('1', '1 - Strongly Agree'), ('2', '2 - Agree'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Disagree (Auto-Enrol)'), ('5', '5 - Strongly Disagree (Auto-Enrol)')], default='', max_length=256, verbose_name='I am confident in my knowledge and usage of Team Work')),
                ('LGA4', models.CharField(choices=[('1', '1 - Strongly Agree'), ('2', '2 - Agree'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Disagree (Auto-Enrol)'), ('5', '5 - Strongly Disagree (Auto-Enrol)')], default='', max_length=256, verbose_name='I am confident in my knowledge and usage of Time Management')),
                ('LGA5', models.CharField(choices=[('1', '1 - Strongly Agree'), ('2', '2 - Agree'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Disagree (Auto-Enrol)'), ('5', '5 - Strongly Disagree (Auto-Enrol)')], default='', max_length=256, verbose_name='I am confident in my knowledge and usage of Computer Applications')),
            ],
        ),
    ]
