# Generated by Django 3.1.3 on 2020-12-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_student_studentpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PathwayName',
            field=models.CharField(choices=[('SO', 'Software Engineering'), ('NE', 'Networking'), ('CO', 'Computing'), ('GD', 'Graphic Design'), ('TE', 'Teacher Education'), ('PE', 'Physical Education'), ('PY', 'Psychology')], max_length=256),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentUsername',
            field=models.CharField(max_length=56),
        ),
    ]
