# Generated by Django 3.1.3 on 2020-12-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201218_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentUsername',
            field=models.CharField(help_text='This information will be used to log you into the website later', max_length=56),
        ),
    ]
