# Generated by Django 3.1.3 on 2020-12-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201219_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentPassword',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentUsername',
            new_name='Username',
        ),
    ]
