# Generated by Django 3.1.3 on 2020-12-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201219_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LGA1',
            field=models.CharField(choices=[('1', '1 - Strongly Agree'), ('2', '2 - Agree'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Disagree (Auto-Enrol)'), ('5', '5 - Strongly Disagree (Auto-Enrol)')], default='', help_text='If you score 3 or higher you will be enroled on the Critical Analysis short course for free. (Cource Reference UOBSCCR2021)', max_length=256, verbose_name='I am confident in my knowledge and usage of Critical Analysis'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Password',
            field=models.CharField(default='', help_text='This information will be used to log you into the website later', max_length=48),
        ),
        migrations.AlterField(
            model_name='student',
            name='TotalUCAS',
            field=models.CharField(default=0, help_text='Must be at least 104 to apply for a Undergraduate Course', max_length=3, verbose_name='What is your total number of UCAS points?'),
        ),
    ]
