# Generated by Django 3.1.3 on 2020-12-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201219_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LGA1',
            field=models.CharField(choices=[('1', '1 - Strongly Agree'), ('2', '2 - Agree'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Disagree (Auto-Enrol)'), ('5', '5 - Strongly Disagree (Auto-Enrol)')], default='', help_text='I am confident in my knowledge and usage of Critical Analysis. If you score 3 or higher you will be enroled on the Critical Analysis short course for free. (Cource Reference UOBSCCR2021)', max_length=256, verbose_name='Critical Analysis'),
        ),
        migrations.AlterField(
            model_name='student',
            name='TotalUCAS',
            field=models.CharField(default=0, help_text='Must be more then 104', max_length=3, verbose_name='What is your total number of UCAS points? (At least 104 needed to apply for a Undergraduate Course)'),
        ),
    ]
