# Generated by Django 3.1.3 on 2020-12-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201219_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LGA1',
            field=models.CharField(choices=[('1', '1 - Very Confident with Critical Analysis'), ('2', '2 - Confident with Critical Analysis'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Not Confident with Critical Analysis (Auto-Enrol)'), ('5', '5 - No Prior Knowledge of Critical Analysis (Auto-Enrol)')], default='', help_text='If you score 3 or higher you will be enroled on the Critical Analysis short course for free. (Cource Reference UOBSCCR2021)', max_length=256, verbose_name='Critical Analysis'),
        ),
        migrations.AlterField(
            model_name='student',
            name='LGA2',
            field=models.CharField(choices=[('1', '1 - Very Confident with'), ('2', '2 - Confident'), ('3', '3 - Unsure (Auto-Enrol)'), ('4', '4 - Not Confident (Auto-Enrol)'), ('5', '5 - No Prior Knowledge (Auto-Enrol)')], default='', max_length=256, verbose_name='I am confident in my knowledge and usage of Technical Documentation'),
        ),
    ]
